language: c
sudo: false
 
# Blacklist
branches:
  except:
    - gh-pages
 
env:
  global:
     - PRETTYNAME="KONNEKTING Device Library"
     - DOXYFILE: $TRAVIS_BUILD_DIR/doxygen-config
 
before_install:
   - source <(curl -SLs https://raw.githubusercontent.com/adafruit/travis-ci-arduino/master/install.sh)
 
install:
   - arduino --install-library "OneWire","DallasTemperature","SparkFun HTU21D Humidity and Temperature Sensor Breakout"
 
script:
#   - build_main_platforms
    - build_platform uno
    - build_platform leonardo
    - build_platform zero
    - build_platform esp8266
 
# Generate and deploy documentation
after_success:
#  - source <(curl -SLs  https://raw.githubusercontent.com/adafruit/travis-ci-arduino/master/library_check.sh)
#  - source <(curl -SLs  https://raw.githubusercontent.com/adafruit/travis-ci-arduino/master/doxy_gen_and_deploy.sh)
